spring:
  application:
    name: springboot-minio

  datasource:
    url: jdbc:mysql://liuyuncen.com:3388/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: cloud
    password: cloud
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

#自定义配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: I7ZLyrAR64D3ZfzTY2uo
  secretKey: 1OYsnV8OoDZb4kVAM24W9olQHNN1nTkv9f8YmpSf
  bucket: user-bucket


