spring:
  application:
    name: springboot-minio

  datasource:
    url: jdbc:mysql://192.168.11.128:3306/minio?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

#自定义配置
minio:
  endpoint: http://192.168.11.128:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: user-bucket


